apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: mainapp-volume
          persistentVolumeClaim:
            claimName: mainapp-claim
      containers:
        - name: pingpong-app
          image: yves6000/pingpong-app:2.1
          volumeMounts: # Mount volume
            - name: mainapp-volume
              mountPath: /usr/src/app/files