apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc

spec:
  type: ClusterIP
  selector:
    app: pingpong-app
#  ports:
#    - port: 2346
#      protocol: TCP
#      targetPort: 3000
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080