apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteapp
  template:
    metadata:
      labels:
        app: noteapp
    spec:
      containers:
        - name: note-app
          image: yves6000/note-app