apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
        - name: main-app
          image: yves6000/main-app:1.15