apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes: # Define volume
        - name: hash-file
          emptyDir: {}
      containers:
        - name: main-app-writer
          image: yves6000/main-app-writer:1.3
          volumeMounts: # Mount volume
            - name: hash-file
              mountPath: /usr/src/app/files
        - name: main-app-reader
          image: yves6000/main-app-reader:1.5
          volumeMounts: # Mount volume
            - name: hash-file
              mountPath: /usr/src/app/files