apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mainapp-claim
  namespace: main-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi