apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noteapp-claim
  namespace: noteapp-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi